backend/Application/Api/Rest/ExportController.cs
backend/Application/Api/Rest/RewardsCsvController.cs

Provide a solution for users wanting to export a full account statement. No support for filtering is implemented. It could make sense to add optional time bounds.
Part of epic "Export transactions from CCDScan".
Most accounts will process in less than 1s. Account `35CJPZohio6Ztii2zy1AYzJKvuxbGG44wrBn7hLHiYLoF2nxnh` which as of this writing has 4339327 statement entries takes 5-6 secs locally and results in a 200MB download (and has too many entries for spreadsheets to open it). This could be used maliciously, so adding some form of rate limiting may be desirable.
Add endpoint `/rest/export/statement?accountAddress=<account-address>` to the backend that responds with a CSV file `statement-<account-address>.csv` containing all records formatted like:
```csv
Time,Amount (CCD),Label …
```

Backend: Add endpoint for exporting account statement as CSV file

---

backend/Application/appsettings.Development.json
backend/README.md
backend/Tests/TestUtilities/DatabaseFixture.cs
frontend/nuxt.config.ts

By default we should expect development to happen against a local Node and TimescaleDB. At least, the current values don't point at anything that's up anymore.
Make default DB connection string and Node gRPC address point to services on localhost.

Use localhost for development

---

frontend/nuxt.config.ts

The Nitro preset is defined to `firebase` as that is what we use in production. If you build your own private instance, you probably want to be able to run it in a local node.js instance instead of deploying to Firebase.
The variable `NITRO_PRESET` should override this but didn't until [Nitro v0.5.0](https://github.com/unjs/nitro/releases/tag/v0.5.0) ([commit](https://github.com/unjs/nitro/commit/92d711fe936fda0ff877c23d8a0d73ed4ea4adc4)). It's not easy to figure out which version of Nitro we use in this project, but the variable doesn't work, and judging by timing, it's clearly an earlier version than this.
Currently the workaround used [here](https://github.com/bisgardo/concordium-docker/pull/53/files) is to completely overwrite `nuxt.config.ts` which is not a great solution.
Read …

Add workaround to NITRO_PRESET not taking precedence

---

frontend/nuxt.config.ts
frontend/src/components/Accounts/AccountDetailsAccountStatement.vue
frontend/src/components/Accounts/AccountDetailsContent.vue
frontend/src/components/Pagination.vue

Expose account statement export (#15) as a button in the frontend.
Add an "Export" button in the account export widget.
*Before:*
*After:*

Frontend: Add account statement export button

---

README.md
backend/ConcordiumSdk/NodeApi/GrpcNodeClient.cs
backend/Dockerfile

Support Node communication via HTTPS.
Use `ChannelCredentials.SecureSsl` if Node address starts with `https:`.
The solution has been verified to work against `https://reporters.internal.testnet.concordium.com:10000`.

gRPC: Use secure credentials for HTTPS address

---

backend/Application/Api/Rest/ExportController.cs

Make it possible to limit the size of the export.
Add optional parameters `fromTime` and `toTime` to let the caller to set time-based limits on what entries to export.
Both parameters expect the time to be provided in ISO 8601 format including time zone (or "Z" for GMT).
The feature is not yet exposed on the frontend as it isn't clear if/how it should be done.
If the statement for an account has no entries, then the string "Nothing to export" is returned instead of a file. If the browser ran into this case, it would change the page to this one. But the frontend already renders "No entries" for accounts with an empty statement, so this case cannot occur.

Backend: Export: Add support for optional time limits

---

backend/Application/Api/GraphQL/EfCore/EntityTypeConfigurations/PaydayStatusConfiguration.cs
backend/Application/Api/GraphQL/Import/MetricsWriter.cs
backend/Application/Api/GraphQL/Import/PaydayImportHandler.cs
backend/Application/Api/GraphQL/Payday/PaydayStatus.cs
backend/CHANGELOG.md
backend/DatabaseScripts/SqlScripts/0037_AlterTable_graphql_payday_status_add_protocol_version.sql
backend/Tests/Api/GraphQL/EfCore/PaydayStatusConfigurationTest.cs

Fixes
- https://github.com/Concordium/concordium-scan/issues/35
- https://github.com/Concordium/concordium-scan/issues/36
On Testnet the protocol 5 is updated at block `1385825`. The last block as the NextPayDayTime of `22/11/2022 11:00:32`
While Block `1385825` has the payday time of `23/11/2022 11:05:19` causing the duration to be calculated to 287 seconds when it should be ~1day (24 * 60 * 60) seconds. Causing the fixed issues.

New Payday On Protocol Update

---

frontend/package.json
frontend/src/pages/blocks/index.vue

Remove Finalization Time Chart until endpoint BlockInfo on nodes has updated, which block last finalized points to.
When fixed, another PR already exist which fixes calculations of finalization times
https://github.com/Concordium/concordium-scan/pull/91
Remove Finalization Time Chart from Block page.

Removing Finalization Time Chart

---

backend/Application/Aggregates/Contract/ContractAggregate.cs
backend/Application/Application.csproj
backend/Tests/Aggregates/Contract/ContractAggregateTests.cs
frontend/package.json

Moved Contract Call event before a Contract Update event, since in the case where a contract call’s itself it will make most sense to have the Contract Call event shown first.
See example below
- Moved Contract Call and Contract Update event types
- Bump front- and backend versions to prepare for release
Task
https://concordium.atlassian.net/browse/CBW-1250

Moved Contract Call Event Before Contract Update

---

frontend/package.json
frontend/src/components/Navigation/DesktopNavigation.vue
frontend/src/components/Navigation/MobileNavigation.vue
frontend/src/components/Search/Search.vue

Due to introduction of new tab ‘Contract’ the search result columns was overlapping. This PR fixes this.
Bug
- https://concordium.atlassian.net/browse/CBW-1364
- Change Search Result View from going to full screen at screen size LG (1024) instead of XL (1280).
- Change navigation tabs from going to burger style at screen size less than XL (1280) instead of first at LG (1024)

Fix overlapping Search Results

---

frontend/package.json
frontend/src/components/atoms/Tooltip.vue

Text wrap in was done using `text-wrap` which wasn’t supported in Firefox and Safari browser. This PR changes to use `white-space: normal` which works across browsers.
* ´text-wrap`
https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap#browser_compatibility
* `white-space`
https://developer.mozilla.org/en-US/docs/Web/CSS/white-space#browser_compatibility

Fix text wraps in tooltips

---

frontend/package.json
frontend/src/components/Contracts/ContractDetailsRejectEvents.vue

Fix missing place where it was receive name instead og entrypoint and contract name was still prefixed.

Fix naming from Receive name to Entrypoint

---

frontend/package.json
frontend/src/components/Contracts/ContractDetailsContainer.vue
frontend/src/components/Contracts/ContractDetailsContent.vue
frontend/src/components/Details/DetailsTable.vue
frontend/src/components/Module/ModuleDetailsContainer.vue
frontend/src/components/Module/ModuleDetailsContent.vue
frontend/src/queries/useContractQuery.ts
frontend/src/queries/useModuleQuery.ts

When paginate through pages in tables there are some load time in contracts with a lot of events. Currently it isn’t easy for the user to see a load is happening which is why blur is added.
Blur details tails when using pagination and data is loading.

Blur tables when fetching data

---

backend/Application/Aggregates/Contract/Configurations/TypeHandlers.cs
backend/Application/Aggregates/Contract/Entities/Contract.cs
backend/Application/Api/GraphQL/EfCore/Converters/EfCore/EfCoreSerializerOptionsFactory.cs
backend/Application/Application.csproj
backend/Tests/Api/GraphQL/__snapshots__/committed-schema.verified.graphql

When query contract which a LOT of events some contract query may take >10 sec. By changing from Entity Framework generated queries to custom I go from 13 sec -> 3 sec on some request.
Changes from using Entity Framework generated SQL queries to more lightweight custom writing.

Optimize contract query

---

backend/rust-bindings/src/lib.rs

Refactor of interop glue code. (Easier to show it)
I'm not sure it needs to use a closure, but it was mainly to isolate the handling of the results, and writing the to result variable.

Refactor rust-bindings to reduce glue code

---

frontend/src/components/Details/DateTimeWithLineBreak.vue

Correct date and time rendering to display them on multiple lines. The previous implementation did not consider that date and time formats vary with different internationalizations.

Fix date time rendering

---

frontend/src/utils/translateTransactionTypes.ts

Add update event types to mapping such that they aren’t mapped as unknown.
Bug: https://concordium.atlassian.net/browse/CBW-1505

Add missing update types

---

backend/Application/Api/GraphQL/Bakers/BakerPool.cs
backend/Application/Api/GraphQL/Bakers/CommissionRates.cs
backend/Application/Api/GraphQL/Bakers/CurrentPaydayStatus.cs
backend/Application/Api/GraphQL/EfCore/EntityTypeConfigurations/BakerConfiguration.cs
backend/Application/Api/GraphQL/Import/BakerImportHandler.cs
backend/Application/Api/GraphQL/Import/MetricsWriter.cs
backend/Application/Application.csproj
backend/CHANGELOG.md
backend/DatabaseScripts/SqlScripts/0047_alter_table_graphql_bakers_add_payday_commissions.sql
backend/Tests/Api/GraphQL/EfCore/BakerTest.cs
backend/Tests/Api/GraphQL/Import/BakerImportHandlerTests.cs
backend/Tests/Api/GraphQL/Import/BakerWriterTest.cs
backend/Tests/Api/GraphQL/__snapshots__/committed-schema.verified.graphql

Add columns for payday commissions on baker. These are only populated from payday blocks and are constant throughout the payday.
The current commissions value on the baker changes instantly on all baker commission configuration and possible chain parameters. Hence these doesn’t give the actual current payday commission but instead show the most recent commission change.
By adding columns for payday commissions one can always see if there are pending changes to commissions, by comparing the current payday commissions and the those from their latest change.
https://concordium.atlassian.net/browse/CBW-1484
https://concordium.atlassian.net/browse/CBW-1485
* Add columns to table `graphql_baker` with current payday commissions
* Populated current payday commissions on payday blocks …

Adding payday commissions

---

backend/Application/Aggregates/Contract/ContractAggregate.cs
backend/Application/Aggregates/Contract/Jobs/InitialContractAggregateCatchUpJob.cs
backend/Application/Aggregates/Contract/Observability/ContractMetrics.cs
backend/Application/Api/GraphQL/Import/ImportWriteController.cs
backend/Application/Application.csproj
backend/Application/Observability/ApplicationMetrics.cs

Add duration metric for main import flow.
* Add duration metric for main import flow
* Migrated contract import metric to the generic one

Main import duration metric

---

frontend/package.json
frontend/src/components/atoms/InfoTooltip.vue
frontend/src/components/atoms/TextCopy.vue
frontend/src/components/atoms/Tooltip.vue
frontend/src/composables/useTooltip.ts

In PR https://github.com/Concordium/concordium-scan/pull/154/files, tooltips were rewritten to simpler logic. However, this logic caused problems when containers were nested within multiple position absolute or fixed elements.
This PR migrates back to more complex logic using transform and translate but fixes a bug where tooltips were shown below elements. In this case, the size of the tooltip was incorrectly used to determine the tooltip position, instead of using the size of the element for which a tooltip should be shown.
* Fix bug when tool tips shown below element.

Fix transformation for tooltips below elements

---

backend/Application/Api/GraphQL/Accounts/Account.cs
backend/Application/Api/GraphQL/Accounts/AccountReleaseScheduleItem.cs
backend/Application/Api/GraphQL/Accounts/AccountReward.cs
backend/Application/Api/GraphQL/Accounts/AccountStatementEntry.cs
backend/Application/Api/GraphQL/Accounts/AccountTransactionRelation.cs
backend/Application/Api/GraphQL/Accounts/AccountsQuery.cs
backend/Application/Api/GraphQL/Bakers/Baker.cs
backend/Application/Api/GraphQL/Bakers/BakerPool.cs
backend/Application/Api/GraphQL/Bakers/BakerTransactionRelation.cs
backend/Application/Api/GraphQL/Bakers/BakersQuery.cs
backend/Application/Api/GraphQL/Bakers/PaydayPoolReward.cs
backend/Application/Api/GraphQL/Blocks/Block.cs
backend/Application/Api/GraphQL/Blocks/BlocksQuery.cs
backend/Application/Api/GraphQL/Blocks/FinalizationSummary.cs
backend/Application/Api/GraphQL/ChainParametersGraphql/ChainParametersQuery.cs
backend/Application/Api/GraphQL/Import/ImportStateQuery.cs
backend/Application/Api/GraphQL/PassiveDelegations/PassiveDelegation.cs
backend/Application/Api/GraphQL/PassiveDelegations/PassiveDelegationQuery.cs
backend/Application/Api/GraphQL/Payday/PaydayQuery.cs
backend/Application/Api/GraphQL/Payday/PaydayStatus.cs
backend/Application/Api/GraphQL/Payday/PaydaySummary.cs
backend/Application/Api/GraphQL/Search/SearchResult.cs
backend/Application/Api/GraphQL/Tokens/Token.cs
backend/Application/Api/GraphQL/Transactions/Transaction.cs
backend/Application/Api/GraphQL/Transactions/TransactionResult.cs
backend/Application/Api/GraphQL/Transactions/TransactionsQuery.cs

Tired of warnings in Github actions because of the use of obsolete attribute.
Followed migration to get rid of the warnings
https://chillicream.com/docs/hotchocolate/v13/migrating/migrate-from-12-to-13/#scopedserviceattribute

Remove deprecated attribute

---

backend/Application/Api/GraphQL/Import/AccountLookup.cs
backend/Application/Import/ConcordiumNode/ConcordiumNodeClient.cs
backend/Tests/Api/GraphQL/Import/AccountLookupTest.cs
backend/Tests/Api/GraphQL/Import/TransactionsWriterTest.cs
backend/Tests/Api/GraphQL/Network/ClientVersionComparerTest.cs

This PR is preparation for step 2, **Migrate all token logic to contract flow, such that token events can be enriched with deserialised messages.**, which will follow PR https://github.com/Concordium/concordium-scan/pull/161.
It enables the account cache to be updated from the node. In theory since account is imported in the main import flow of the CCD scan and contracts in another import flow, it could be the contract flow needs to process information from an account, which hasn’t yet been imported to the database.
By enabling the account cache to lookup the account index on the node and not only the database, we ensure the account cache can be used in other flows than the one which imports account.
- Add to account cache look up of account index on the node if it isn’t present in either …

Add node query to account cache lookup

---

backend/Dockerfile

Interop calls to rust binaries has stopped working in the CCD scan after migrating to binaries in the .NET SDK. The issue was only seen when building  and running CCD scan docker image.
The issue is that the binaries in the .NET SDK are build on Ubuntu 22.04
https://github.com/Concordium/concordium-net-sdk/actions/runs/7209178248/job/19639595963
The CCD scan docker images were using mcr.microsoft.com/dotnet/aspnet:6.0 which relies on Debian 11.
https://github.com/dotnet/dotnet-docker/blob/main/README.runtime.md#full-tag-listing
By looking at the shared object dependencies needed for the `librust_bindings.so` build on Ubuntu 22.04 and used in Debian 11 we see that some dependencies are missing
```
./librust_bindings.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found …
```

Bump Debian version in docker image

---

backend/Application/Api/GraphQL/Accounts/Account.cs
backend/CHANGELOG.md

Sort tokens by contract- index, subindex and token id.
Issue seen on testnet
https://testnet.ccdscan.io/tokens?dcount=1&dentity=account&daddress=3iCW2ejiWLhB3zNWafhg457X1TqzrkSouosjz8gf4kCifGFZo4
Now sorted as below
Issue: https://concordium.atlassian.net/browse/CBW-1660
- Change query to sort by contract- index, subindex and token id instead of index indicating when the token was created.

Sort by contract- index, subindex and token id in Account token view

---

backend/Application/Aggregates/Contract/Configurations/TokenConfiguration.cs
backend/Application/Aggregates/Contract/Entities/Token.cs
backend/Application/Aggregates/Contract/EventLogs/EventLogWriter.cs
backend/Application/Aggregates/Contract/Extensions/ContractExtensions.cs
backend/Application/Aggregates/Contract/Jobs/_06_AddTokenAddress.cs
backend/DatabaseScripts/SqlScripts/0050_alter_table_graphql_tokens_add_column_token_address.sql
backend/Tests/Aggregates/Contract/Entities/TokenTestWithoutDatabase.cs
backend/Tests/Aggregates/Contract/EventLog/EventLogWriterTest.cs
backend/Tests/Aggregates/Contract/Jobs/_06_AddTokenAddressTest.cs

This is the first out of two PR’s which enables tokens to be searchable by token address.
This first PR migrates the database to extend token table with column for token address.
Second PR: https://github.com/Concordium/concordium-scan/pull/178
Task: https://concordium.atlassian.net/browse/CBW-1658
- Extend `graphql_tokens` with column `token_address`
- Add migration jobs, which iterates through all existing tokens and enrich entities with token adress

Token address searchable - migration

---

backend/Application/Aggregates/Contract/Entities/Token.cs
backend/Application/Application.csproj
backend/Tests/Api/GraphQL/__snapshots__/committed-schema.verified.graphql
backend/Tests/Api/Rest/ExportControllerTest.cs
frontend/package.json
frontend/src/components/Contracts/ContractDetailsTokens.vue
frontend/src/components/Tokens/TokenDetailsContent.vue
frontend/src/pages/tokens/index.vue
frontend/src/types/generated.ts

Token amounts are up to 256 bits so they don't fit into a decimal.
I believe this should be sufficient since all the actual updates to the amount are via SQL, and there the value that is added is always a BigInteger. So the value stored in the database is always an integer.
But ideally that would also be changed in the column type from "numeric" to "biginteger'.
The "decimal" makes it so that tokens cannot be read from the database and in particular the data migration job fails sometimes.
```
2024-02-17 19:30:10.575 [EROR] [Application.Jobs.JobsBackgroundService`2[[Application.Aggregates.Contract.Jobs.IContractJob, Application, Version=1.8.13.0, Culture=neutral, PublicKeyToken=null],[Application.Aggregates.Contract.Entities.ContractJob, Application, Version=1.8.13.0, Culture=neutral, …
```

Token amounts can be more than what decimal fits.

---

frontend/package.json
frontend/src/components/Navigation/DesktopNavigation.vue
frontend/src/components/Navigation/MobileNavigation.vue
frontend/src/components/Search/Search.vue

Search field were unable to be utilized at certain widths.
Issue: https://github.com/Concordium/concordium-scan/issues/184
- Updated navigation icons at wider screen widths.

Fix search field

---

backend/Application/Application.csproj
backend/Application/Database/DatabaseMigrator.cs
backend/Application/Database/DatabaseSettings.cs
backend/Application/appsettings.json
backend/CHANGELOG.md
backend/DatabaseScripts/SqlScripts/0053_create_index_on_graphql_account_statement_for_rewards.sql

See task for full discussion: https://concordium.atlassian.net/browse/CD-947
Initial task: https://github.com/Concordium/concordium-scan/issues/17
Prior PR (which will be closed): https://github.com/Concordium/concordium-scan/pull/60 
Successfully created an index which overrules default index `graphql_account_statement_entries_pkey`.
By looking at the execution plan
```
explain (analyse, verbose, buffers, summary, costs, settings, wal, timing)
select *
from graphql_account_statement_entries
where account_id = 83271
and entry_type >= 6
order by index desc;
```
We have
```
Index Scan Backward using account_statement_entries_account_id_index_rewards_index on public.graphql_account_statement_entries  (cost=0.56..1055171.74 rows=14113168 width=60) (actual time=0.017..0.018 rows=0 loops=1)
" …
```

Fix performance on view graphql_account_rewards

---

backend/Application/Api/Rest/EnumerableFileResult.cs
backend/Application/Api/Rest/ExportController.cs
backend/Application/Application.csproj
backend/CHANGELOG.md
backend/DatabaseScripts/SqlScripts/0054_create_index_on_graphql_account_statement_for_timestamp.sql
backend/DatabaseScripts/SqlScripts/0054_create_index_on_graphql_account_statement_for_timestampsql
backend/Tests/Api/Rest/ExportControllerTest.cs

Avoid big accounts to timeout (at 30 seconds) when using the export. 
- Add index for account statements on account_id and time.
- Change query to stream data, instead of building a big string.

Export fix

---

frontend/package.json
frontend/src/components/Accounts/AccountDetailsAccountStatement.vue

Allow exporting account statements for the month that an account was created
Set createdAtMonth used for month picker to first day in the month (instead of the specific day the account was created)

Fix bug that blocked exporting account statement for first month in frontend

---

.github/workflows/ci.yml
.gitmodules
backend/Application/Api/GraphQL/Import/AccountWriter.cs
backend/Application/Api/GraphQL/Import/BakerChangeStrategy.cs
backend/Application/Api/GraphQL/Import/BakerImportHandler.cs
backend/Application/Api/GraphQL/Import/BakerWriter.cs
backend/Application/Api/GraphQL/Import/DelegationImportHandler.cs
backend/Application/Api/GraphQL/Import/ImportWriteController.cs
backend/Application/Api/GraphQL/Import/MetricsWriter.cs
backend/Application/Api/GraphQL/Import/PaydayPoolStakeSnapshot.cs
backend/Application/Api/GraphQL/Import/Validations/AccountValidator.cs
backend/Application/Api/GraphQL/Import/Validations/BalanceStatisticsValidator.cs
backend/Application/Api/GraphQL/Import/Validations/IImportValidator.cs
backend/Application/Api/GraphQL/Import/Validations/ImportValidationController.cs
backend/Application/Api/GraphQL/Import/Validations/PassiveDelegationValidator.cs
backend/Application/Application.csproj
backend/Application/Import/ImportChannel.cs
backend/CHANGELOG.md
backend/CcScan.Backend.sln
backend/README.md
backend/Tests/Api/GraphQL/Import/AccountImportHandlerTest.cs
backend/Tests/Api/GraphQL/Import/AccountLookupTest.cs
backend/Tests/Api/GraphQL/__snapshots__/committed-schema.verified.graphql
backend/Tests/TestUtilities/DatabaseFixture.cs

Prepare CCDScan for Concordium Protocol Version 7.
- Fix CI due to `docker-compose` not being available in the ubuntu image anymore (see https://github.com/mariotoffia/FluentDocker/issues/312)
- Added concordium-net-sdk as submodule.
- Introduced some doc comments while learning the codebase.
- Fix bug in validation code, which branched on the node version instead of the protocol version of the block.
- Handle new events for configuring delegation and validators.
- Make stake changes immediate for protocol version 7 blocks and onwards, ignoring pending changes from this point on.

Support Concordium Protocol Version 7

---

backend/Application/Application.csproj
backend/Dockerfile

Fix build, which now depends on the Rust tool chain.
- Update `backend/Dockerfile` to install Rust during build.
- Remove unused build conditions from `backend/Application.csproj`.

Update dockerfile  adding rust toolchain

---

backend/Application/Aggregates/Contract/ContractAggregate.cs
backend/Application/Aggregates/Contract/ContractRepository.cs
backend/Application/Aggregates/Contract/Jobs/_04_InitialContractEventDeserializationFieldsCatchUpJob.cs
backend/Application/Aggregates/Contract/Jobs/_05_CisEventReinitialization.cs

Fixes the reported error
```
2024-06-06 07:17:05.588 [DBUG] [Application.Aggregates.Contract.ContractAggregate] [00-21a79dd04dd68545abe08571361feafe-b5438bc22109a2d6-00] Reading block a38f0e17c1aa481248d555bbf9a57f5487425782b580731beba12da336c2bd50, at height 2566608
2024-06-06 07:17:05.597 [EROR] [Application.Aggregates.Contract.ContractAggregate] [00-21a79dd04dd68545abe08571361feafe-5d8d4989a06a906f-00] Got exception running NodeImportJob will try again with 21552
System.InvalidOperationException: Sequence contains no elements.
at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSou …
```

Implements `IModuleReadonlyRepository` trait on `IContractRepository`

---

backend/Application/Api/GraphQL/ChainParameters.cs
backend/Application/Api/GraphQL/Import/ImportWriteController.cs
backend/Application/Api/GraphQL/Import/MetricsWriter.cs
backend/Application/Application.csproj
backend/CHANGELOG.md
backend/Tests/Api/GraphQL/Import/MetricsWriterTest.cs

Fix issue where backend is crashing when protocol update is effective within the same second as the next payday.
This results in a payday duration rounded to `0` seconds, which is an issue for the current computation of APY.
This PR changes the APY computation to be based on the expected payday length instead of the last measured payday length.
Also updated the changelog and prepared for release 1.9.1

Compute APY using the expected payday duration instead of last duration

---

backend-rust/src/graphql_api.rs
backend-rust/src/graphql_api/transaction_metrics.rs

Just a tiny cleanup after @DOBEN's review of #274

Tiny cleanup

---

backend/Application/Api/GraphQL/Import/DelegationImportHandler.cs
backend/Application/Application.csproj
backend/CHANGELOG.md

Fix bug preventing the ingestion from proceeding.
The issue was that delegators with pending changes from P6 were not migrated immediately in P7, as the migration logic was only run at payday.
This PR changes the migration logic to be run at every block ingested in P7.

Run P7 delegator migrations at every P7 block instead of only payday

---

.github/workflows/frontend-release.yml

Release fails due to a change in the value `secrets.DOCKER_USERNAME` as the value is now `concordium` (not really a secret) and GitHub therefore prevents it from being used anywhere else in the workflow.
The fix is to avoid using a secret for storing the username, allowing `concordium` to be used elsewhere.

Hardcode docker username as the secret

---

backend-rust/migrations/0001_initialize.up.sql
backend-rust/src/graphql_api.rs

I'm honestly not sure where this is used in the frontend.
Added the `AccountsUpdatedSubscriptionItem` and the appropriate methods to `Subscription`, which are largely inspired by the already-existing `block_added` subscription.
What's missing is actually sending the notifications when the appropriate event happens - this is left for future work.

Accounts updated subscription

---

backend-rust/migrations/0001_initialize.up.sql
backend-rust/src/graphql_api.rs

Add decoding of contract log events in interrupt chain events
Add decoding of contract log events in interrupt chain events

Add decoding of contract log events

---

backend-rust/Cargo.lock
backend-rust/Cargo.toml
backend-rust/migrations/0001_initialize.up.sql
backend-rust/migrations/0002_account_notify.down.sql
backend-rust/migrations/0002_account_notify.up.sql

Data has been migrated, and a deployment has occurred. Hence now we need to migrate new sql into a separate script. (Basically also just good idea to start practicing it). It is already on stagenet, and it did make the migration work.

Moved to new sql structure

---

frontend/package.json
frontend/src/queries/useAccountQuery.ts

I can ignore pendingChange as per https://linear.app/concordium/issue/CCD-68/implement-accountdelegation on fungy CCDScan as soon as we stop querying it on the frontend. It does not seem to be used.

Remove unused field in the frontend

---

backend-rust/.sqlx/query-6af2928df158730d8a4cc3f4e7284ac67825a548794ce2b9c3246d642cc013d5.json
backend-rust/.sqlx/query-71525908726653a43c0cf1b0515fb5d8aa6e0405d54781b6220a573e797e6e34.json
backend-rust/.sqlx/query-c2ce5d93c3680bd913787a573d825838f2f8ea2a09181e30e5035374bf51727b.json
backend-rust/src/graphql_api.rs
backend-rust/src/graphql_api/account_metrics.rs
backend-rust/src/indexer.rs

```
{
"data": null,
"errors": [
{
"message": "Unknown field \"accountsMetrics\" on type \"Query\". Did you mean \"accountMetrics\", \"accountByAddress\"?",
"locations": [
{
"line": 2,
"column": 3
}
]
}
]
}
```
Modified name to be accountsMetrics for backwards compatibility
Added missing events to database structs conversion
CreatedAt is taking in an option making it not working.

Fixing errors related to account and account delegation

---

backend-rust/src/bin/ccdscan-api.rs
backend-rust/src/graphql_api.rs

Predecessor to: https://linear.app/concordium/issue/CCD-114/add-health-check-endpoint
When db shuts down we are shutting down entire api, leaving it to SRE to recover from a bad situation. 
Retry on errors.

Keep api alive

---

frontend/CHANGELOG.md
frontend/src/queries/useAccountListQuery.ts

Improve query performance by removing unused `Account::transactions` sub query.

Remove unused subquery for accounts transaction in accounts page

---

backend-rust/src/graphql_api.rs
backend-rust/src/graphql_api/account_metrics.rs
backend-rust/src/graphql_api/block.rs
backend-rust/src/graphql_api/block_metrics.rs
backend-rust/src/graphql_api/transaction.rs
backend-rust/src/graphql_api/transaction_metrics.rs

Rename `Query` in `graphql_api` modules due to `async_graphql` crate produces a runtime error due to name conflict

Rename Query in graphql_api modules due to async_graphql name conflict

---

backend-rust/src/graphql_api.rs
backend-rust/src/graphql_api/baker.rs
backend-rust/src/graphql_api/contract.rs
backend-rust/src/graphql_api/module_reference_event.rs
backend-rust/src/graphql_api/token.rs
backend-rust/src/indexer.rs
backend-rust/src/transaction_event/smart_contracts.rs

Move `Baker`, `ModuleReferenceEvent`, `Contract` and `Token` together with related types to separate files.

Splitup graphql_api

---

backend-rust/src/indexer.rs

Allow preprocessing to proceed when CIS-0 queries fail.
Failing the CIS-0 `supports` query will fall back to the assumption of no support.

Avoid failing preprocessing due to CIS-0 errors

---

backend-rust/migrations/0001_initialize.up.sql

While running the indexer on testnet I found some queries to take a while.
This PR adds and adjusts index in order to improve this.

Add index for blocks without fin_time and contract_events

---

backend-rust/.sqlx/query-3c6ebfdb85f26d0ca0cf19e3e00e9e30b13e547d8c1f075c4dde7136eae72ef3.json
backend-rust/src/graphql_api/contract.rs

The query `Query::contracts` in the new rust backend needs to be descending order like the old backend.

Use DESC order for contract connection query

---

backend-rust/Cargo.lock
backend-rust/Cargo.toml
backend-rust/src/bin/ccdscan-api.rs
backend-rust/src/bin/ccdscan-indexer.rs

```
indexer_service_info{version="0.1.10"} 1
```
Instead of 
```
indexer_service_info{version="0.1.9"} 1
```
Since info is not a valid metric type causing the collector to fail

Fix metrics type

---

frontend/src/queries/useTokenQuery.ts

Remove `updateOperator` case in `tokenEvents` since the  `updateOperator` event is contract-specific but not token-specific.

Remove update operator event from token events

---

backend-rust/src/graphql_api/block.rs

Fix inconsistency.
The graphql API of the .NET backend expects the argument to be named differently.

Align parameter for Query::block to match .NET backend

---

backend-rust/.sqlx/query-3c68bcd07cc8ddee8de17f2996ece8aa625aa70aef64153347f79d84e9dd9a6b.json
backend-rust/.sqlx/query-c5a51f14dfc01a5a58aa0f6b7611953ec6a16b1a4aeef0e4dcd5e4fc24ad2ff1.json
backend-rust/src/graphql_api/block.rs

Adjust the block list query to use descending order.
Compute the flags for next and previous page as well.

Order blocks descendingly and compute the next/previous page

---

frontend/.env.stagenet
frontend/CHANGELOG.md
frontend/nuxt.config.ts
frontend/src/queries/useBlockListQuery.ts
frontend/src/queries/useBlockQuery.ts
frontend/src/queries/useChartBlockMetrics.ts
frontend/src/queries/useContractQuery.ts
frontend/src/queries/useContractsListQuery.ts
frontend/src/queries/useModuleQuery.ts
frontend/src/queries/useTokenQuery.ts
frontend/src/queries/useTokensListQuery.ts

Set up the frontend to use the new backend for block page, contract page and token page.
Affected queries:
- `useBlockListQuery`
- `useBlockQuery`
- `useChartBlockMetrics`
- `useContractQuery`
- `useContractsListQuery`
- `useModuleQuery`
- `useTokenQuery`
- `useTokenListQuery`

Have frontend use new backend

---

.github/workflows/release-net-backend.yaml
backend/Application/Application.csproj

Release .NET backend 1.10.0
I already update the changelog in my previous PR, but for forgot to update the version in the code.
Also, change the new release pipeline for .NET backend to use the tag previously used by backend.

Release .NET backend 1.10.0

---

backend-rust/Cargo.lock
backend-rust/Cargo.toml
backend-rust/src/indexer.rs
backend-rust/src/transaction_event/mod.rs

The database is complaining about unsupported unicode characters again, so I moved the sanitizing code into where we construct the types instead of right before inserting.

Sanitize metadata url

---

backend-rust/src/indexer.rs

Fix error where we were fetching block certificates for blocks prior to P6, causing invalid argument gRPC error.
- Only update bakers unmarking primed for suspension starting from P8

Only fetch blocks when starting from P6

---

backend-rust/Cargo.lock
backend-rust/Cargo.toml
backend-rust/src/transaction_type.rs

Indexer is failing due to missing implementation of the P8 update transaction type for the validator score

Fix missing P8 Update transaction type

---

backend-rust/src/bin/ccdscan-api.rs
backend-rust/src/bin/ccdscan-indexer.rs
backend-rust/src/router.rs

- Change health checks to validate the database schema version.
- Provide flag for `ccdscan-api` which can be used for validating the database schema before spinning up the service.

Make health endpoints check database schema version

---

backend-rust/src/indexer.rs

Fix issue when fetching genesis information from node endpoint depending on TLS.
We already handle TLS, but not until the main indexer start running, so this PR move the handling earlier so it applies for the genesis data fetching as well.

TLS and timeouts for endpoints when fetching genesis data

---

backend-rust/.env.mainnet
backend-rust/.env.stagenet
backend-rust/.env.testnet
backend-rust/src/bin/ccdscan-api.rs
backend-rust/src/bin/ccdscan-indexer.rs

Add `--dovenv <file>`  option to both binaries, useful when running the service for several environments.

Provide option to point to different .env file

---

backend-rust/src/graphql_api.rs
backend-rust/src/graphql_api/account.rs
backend-rust/src/graphql_api/block.rs
backend-rust/src/graphql_api/token.rs

Remove `#![allow(unused_variables)]` from `graphql_api.rs` and address the warnings

Disallow unused variables in graphql_api.rs

---

backend-rust/src/bin/ccdscan-api.rs
backend-rust/src/graphql_api.rs

Change `--schema-out <file>` argument for `ccdscan-api` to exit immediately.
Later we will use this as part of the CI to generate the schema and ensure that we don't introduce changes by accident.

Change --schema-out <file> argument for ccdscan-api to exit immediately

---

backend-rust/Cargo.lock
backend-rust/Cargo.toml
backend-rust/src/bin/ccdscan-api.rs
backend-rust/src/bin/ccdscan-indexer.rs
backend-rust/src/graphql_api/node_status.rs

Health endpoint should return a none 200 status code given it is in a invalid state to comply with http probe.
Change status code on health endpoint
Add failed metrics counter on fetch on against the node collector backend

Health endpoint

---

frontend/CHANGELOG.md
frontend/src/queries/useBlockSpecialEventsQuery.ts

Move query `useBlockSpecialEventsQuery` to new API

Move query `useBlockSpecialEventsQuery` to new API

---

frontend/CHANGELOG.md
frontend/src/components/TransactionEventList/Events/ContractUpgraded.vue
frontend/src/queries/useTransactionQuery.ts

Fixes #436 
Bug was introduced as part of the [PR fixing type warnings](https://github.com/Concordium/concordium-scan/pull/291).
Here I revert the changes, disable the warning for these lines and document why.

Fix useTransactionQuery error due to field names clashing

---

backend-rust/src/bin/ccdscan-indexer.rs

We need to return a none zero exit code given migration issues occurs

Migration issues

---

frontend/CHANGELOG.md
frontend/package.json
frontend/src/components/Contracts/ContractDetailsEvents.vue
frontend/src/queries/useContractQuery.ts

Fix bug preventing contract details from being shown and prepare release 1.7.0.
The bug was introduced as part of the [PR fixing type warnings](https://github.com/Concordium/concordium-scan/pull/291).
Here I revert the changes, disable the warning for these lines and document why.

Frontend fix for contract details and release

---

.github/workflows/backend-checks.yml
.github/workflows/backend-net-checks.yml
.github/workflows/frontend-checks.yml

Enable CI checks to run when `edited` to ensure they are run, when PR use another PR as the base branch and the first gets merged.
This event also includes changes to the title of the PR, which is unfortunate but seems like a small thing.

Run CI checks when PR is edited (base branch changes)

---

backend-rust/.sqlx/query-8b160d1140d7823bcaf03711b9934621569d7e66c60aba8cb962054f82a8c2c6.json
backend-rust/CHANGELOG.md
backend-rust/src/migrations/m0001-initialize.sql
backend-rust/src/transaction_event/smart_contracts.rs

Fixes https://github.com/Concordium/concordium-scan/issues/472
- Fix button to display the schema decoding error at the front-end by returning the error as an object.

Improve schema decoding errors

---

frontend/CHANGELOG.md
frontend/src/components/Contracts/ContractDetailsEvents.vue
frontend/src/components/Contracts/ContractDetailsRejectEvents.vue
frontend/src/components/Contracts/Events/ContractCall.vue
frontend/src/components/Contracts/Events/ContractInitialized.vue
frontend/src/components/Contracts/Events/ContractUpdated.vue

Fix https://github.com/Concordium/concordium-scan/issues/461
- Always display the `hexDecimal` representation of logs and messages.

Always display hexDecimal logs and messages

---

backend-rust/src/connection.rs
backend-rust/src/graphql_api.rs
backend-rust/src/graphql_api/account.rs
backend-rust/src/graphql_api/baker.rs
backend-rust/src/graphql_api/block.rs
backend-rust/src/graphql_api/contract.rs
backend-rust/src/graphql_api/token.rs
backend-rust/src/graphql_api/transaction.rs

Rename some variables in `connection.rs` which are named differently from how these are used.
This should not change any semantics of the code.

Fix misleading variable names in connection.rs

---

backend-rust/.sqlx/query-809b53801320323a3355be773064d4fe31dcea326624663b1bfe5fd24d2963af.json
backend-rust/.sqlx/query-9184bfdb5aebf2a9b62399e363e1be7d7f1f79dcda47f0e0d2486b1084ea632a.json
backend-rust/CHANGELOG.md
backend-rust/src/graphql_api/transaction.rs
frontend/CHANGELOG.md
frontend/package.json
frontend/src/queries/useTransactionListQuery.ts
frontend/src/queries/useTransactionMetrics.ts

Use transaction metrics and transaction list from the Rust API.
Also changed the transaction list order from newest -> oldest to match the .NET backend.

Use transaction metrics and transaction list from rust backend

---

frontend/CHANGELOG.md
frontend/src/components/molecules/TransactionLink.vue
frontend/src/pages/transactions/index.vue

Fix transaction links from transaction list page. These failed due to using a transaction ID which is incompatible with the new API, instead only the transaction hash can be used now.
Fix #514

Frontend: Only support transaction hash as identifier and not ID

---

backend-rust/CHANGELOG.md
backend-rust/src/scalar_types.rs

We do not want to show the interval in secs, but a more appropriate unit dependent on size of the timespan

Timespan format

---

backend-rust/.sqlx/query-111042cda533aaaeb74ad51acfe5ece689058acf1dd302c7d429b1e5e2d706f1.json
backend-rust/.sqlx/query-90dfde0be8b6c6aa1d00061e92babe7a89aa36ddce688bbe996a592c3d7a12b5.json
backend-rust/.sqlx/query-f7d67c27717abe9eaeb99b00d681cd75e2215f7574d27b5354610e6d8e769f09.json
backend-rust/CHANGELOG.md
backend-rust/src/graphql_api/baker.rs
backend-rust/src/indexer.rs
backend-rust/src/migrations.rs
backend-rust/src/migrations/m0004.sql
backend-rust/src/scalar_types.rs

Addresses https://github.com/Concordium/concordium-scan/issues/367
```
query ($bakerId: Long!) {
bakerByBakerId(bakerId: $bakerId) {
state {
__typename
... on ActiveBakerState {
pool {
lotteryPower
}
}
}
}
}
```
Related https://linear.app/concordium/issue/CCD-142/implement-bakerpool
Add `lottery power` logic.

Add logic for lottery power

---

backend-rust/src/indexer.rs

Somehow I failed to [address this comment](https://github.com/Concordium/concordium-scan/pull/529#discussion_r1954715788) on previous PR.
Nothing noted in the changelog since this was never released.

Move delegators before removing baker

---

backend-rust/.sqlx/query-b6a021f65c32c86a03655066143410700595922ecfd0f4e4c0165ce0d0e41fc6.json
backend-rust/.sqlx/query-fc16002ac99907e9145d7d8ec90da3c19bd8ee295ce5fe582e4d1d80500ab4c2.json
backend-rust/CHANGELOG.md
backend-rust/src/indexer.rs
backend-rust/src/migrations.rs
backend-rust/src/migrations/m0006_fix_stake.rs

Add handling of restake_earnings in the indexer and introduce migration 6 for updating the current stake from chain.

Handle restaking and update stake

---

backend-rust/CHANGELOG.md
backend-rust/Cargo.lock
backend-rust/Cargo.toml
backend-rust/src/indexer.rs

We are failing because tokens related to smart contracts may not be to/from a valid account.

Fix validation on tokens

---

frontend/CHANGELOG.md
frontend/package.json
frontend/src/queries/useNodeDetailQuery.ts
frontend/src/queries/useNodeQuery.ts

Migrate nodes related endpoints to be using fungy CCDScan
https://linear.app/concordium/issue/CCD-200/frontend-nodes-to-fungy-ccdscan
Closes https://github.com/Concordium/concordium-scan/issues/559

Migrate nodes to be using fungy ccdscan

---

backend-rust/CHANGELOG.md
backend-rust/src/graphql_api/baker.rs

Addresses https://github.com/Concordium/concordium-scan/issues/562
This helps to use the baker query again. Investigation into the formula still needs to be done (the issue stays open and is not addressed).

Use saturated sub at capital bound formula

---

backend-rust/CHANGELOG.md
backend-rust/src/graphql_api/transaction.rs

Enable total count, as is enabled on dotnet version and request by the client. https://github.com/Concordium/concordium-scan/blob/main/backend/Application/Api/GraphQL/Transactions/TransactionResult.cs

Total count

---

backend-rust/CHANGELOG.md
backend-rust/src/graphql_api.rs
frontend/CHANGELOG.md
frontend/src/queries/usePaydayStatusQuery.ts
frontend/src/queries/useTopDelegatorsQuery.ts
frontend/src/queries/useVersionsQuery.ts

Addresses https://github.com/Concordium/concordium-scan/issues/600
-  Change queries `useVersionsQuery`, `useTopDelegatorsQuery` and `usePaydayStatusQuery` to use the new `rust-backend` API.

Migrate queries to new backend

---

backend-rust/CHANGELOG.md
backend-rust/src/indexer.rs
backend-rust/src/migrations/m0019_chain_update_events.rs
backend-rust/src/transaction_event/mod.rs

Alter to be using correct effective time when the value is zero
https://github.com/Concordium/concordium-scan/blob/3eadf9eb6c642ac22203e4884e37f3479d5090d7/backend/Application/Api/GraphQL/Transactions/TransactionResultEvent.cs

Effective time

---

backend-rust/CHANGELOG.md
backend-rust/Cargo.lock
backend-rust/Cargo.toml
backend-rust/src/bin/ccdscan-api.rs
backend-rust/src/bin/ccdscan-indexer.rs

Before setting `--log-level=debug` would result in debug logs from dependency, now it only applies to logs from this crate.
The old behavior can still be triggered by setting environment variable `RUST_LOG=debug`.

Log level only apply for crate logs

---

backend-rust/CHANGELOG.md
backend-rust/src/graphql_api/baker.rs

The underflow fix released in `0.1.33` changed the order of operations, causing the computation to become 0 for some baker pools.
#643

Fix delegated_stake_cap computation

---

backend-rust/CHANGELOG.md
backend-rust/src/bin/ccdscan-api.rs

To help protect against resources being taken up by accidental long-running queries in the API, this PR introduces an option for configuring the [`statement_timeout`](https://www.postgresql.org/docs/16/runtime-config-client.html#GUC-STATEMENT-TIMEOUT) for the connections in the pool of `ccdscan-api`.
Queries exceeding this time will be aborted, freeing up the resources.

Add statement-timeout option for API

---

.github/workflows/backend-checks.yml
backend-rust/CHANGELOG.md
backend-rust/Cargo.lock
backend-rust/Cargo.toml
backend-rust/Dockerfile
backend-rust/src/bin/ccdscan-api.rs
backend-rust/src/graphql_api/baker.rs
backend-rust/src/rest_api.rs

Ref COR-1352
Expand metrics to include the public rest API.
The metrics can be when running the API at (default http://localhost:8003/metrics)
Update rust version to 1.83 since some new dependencies require it.

Add public rest API to the monitoring

---

.github/workflows/graphql-codegen-check.yml

Add CI check which generates the Typescript types from schema.graphql and compares it with the committed version.
Fails if anything (except comments) are different.
[Example of the CI failing can be seen here](https://github.com/Concordium/concordium-scan/actions/runs/14988675493/job/42107352969)

Add CI check for generated types from schema.graphql

---

backend-rust/CHANGELOG.md
backend-rust/src/rest_api.rs

Close [COR-1404](https://linear.app/concordium/issue/COR-1404/export-account-statements-fail-on-mainnet)

Fix export account statement issue

---

backend-rust/Dockerfile

To  enable the docker file to copy the mock json files 
Docker file is changed.

fix: enable docker file to copy the mock json files

---

backend/CHANGELOG.md
backend/src/graphql_api.rs
backend/src/rest_api.rs

Fix Account Statement export (Currently October 2024 fails for exporting due to violating max day range)
The existing max was hardcoded at 31, and the logic from the UI to parse monthly account statement data is to provide the first of the month, and first of the next month to export. For October 2024 - this would be technically 32 days.
Added a new environment property to allow for configuration - defaulting to 32 for now until we have further requirements to investigate and expand the max range.

fix: added configurable property for the account statement max days export 

---

backend/CHANGELOG.md
backend/schema.graphql
backend/src/graphql_api/plt.rs
backend/src/indexer/block/block_item/plt_token_creation.rs
backend/src/transaction_event/chain_update.rs
backend/src/transaction_event/mod.rs
backend/src/transaction_event/protocol_level_tokens.rs
frontend/src/pages/protocol-token/index.vue
frontend/src/types/generated.ts

Fix for - `2025-07-22T13:39:06.641650Z  INFO concordium_scan::indexer::block_preprocessor: Failed preprocessing 11 times in row: Failed to query: RPC error: Error parsing JSON result: Failed to decode initialization parameters: Semantic(None, "invalid value: integer `-250`, expected i8")` 
Remove custom deserialization of InitializationParameter  and used rust-sdk type `TokenModuleInitializationParameters` for proper deserialization of `InitializationParameter`. 

fix: use cbor::cbor_decode for InitializationParameter ( COR-1663 )

---

backend/CHANGELOG.md

The changelog was missing some database schema information, making it hard to figure out where a migration was released, this PR fixes that.

Add missing database schema version to changelog

---

backend/CHANGELOG.md
backend/src/indexer/block_preprocessor.rs

The prometheus gauge metric `node_response_time_seconds` did not reflect the whole picture as it used to count time used during the first phase of two-step block preprocessing. Since second step now also interacts with the node, the metric should have been updated to reflect the change.
* `node_response_time_seconds` metric now covers time needed during the both data fetching and block preparing steps.

COR-1735 node_response_time_seconds metric covers fetching and preparing

---

frontend/CHANGELOG.md
frontend/src/components/atoms/PltAmount.vue
frontend/src/pages/protocol-token/index.vue

Fix build error due to bigInt literals and es2019
Converted literals to BigInt Object ( `0n`  --->  Bigint(0)) 

fix: fix buiild error due to bigInt literals es2019

---

backend/.sqlx/query-cb76ec9ab7d605df2933c05944f72ce1c6a67f8bab3807dcbf3eb10c2ab98f9a.json
backend/CHANGELOG.md
backend/src/transaction_event/protocol_level_tokens.rs

Fix Indexer crashlooping due to plt Transfer to same account as sender and reciever
We don't update the db for balance update if both are same so effective change is 0;

fix: Transfer Plt txn sender and reciver are same CRE-548

---

backend/schema.graphql
backend/src/transaction_event/protocol_level_tokens.rs
frontend/CHANGELOG.md
frontend/src/components/TransactionEventList/Events/PltTransferMemo.vue
frontend/src/components/TransactionEventList/Events/TokenEvents.vue
frontend/src/queries/usePltEventsQuery.ts
frontend/src/queries/useTransactionQuery.ts
frontend/src/types/generated.ts

When transferring PLT tokens with a memo, the memo text is not visible on CCDScan. This behavior is inconsistent with CCD transfers, where the memo is displayed correctly.
- A new `PltTransferMemo` component is added

fix: CRE-531

---

frontend/CHANGELOG.md
frontend/src/components/Charts/ChartBarST.vue
frontend/src/components/Charts/DoughnutChart.vue
frontend/src/components/PageFooter/OpenLinkButton.vue
frontend/src/pages/protocol-token/index.vue

Open per plt page open in the same browser tab
Changed `window.open(`/protocol-token/${label}`, '_blank')`  to `window.open(`/protocol-token/${label}`, '_self')` 

fix: navigation CRE-545
