- frontend/src/components/Accounts/AccountDetailsContent.vue
- frontend/src/components/molecules/TokenLink.vue
Address Review for Tokens Listing PR #6
Address Review for Tokens Listing PR #6
> Address Review for Tokens Listing PR #6

- backend/.gitignore
- backend/Application/Api/GraphQL/Accounts/Account.cs
- backend/Application/Api/GraphQL/Accounts/AccountToken.cs
- backend/Application/Api/GraphQL/EfCore/EntityTypeConfigurations/AccountTokenConfiguration.cs
- backend/Application/Api/GraphQL/GraphQlConfiguration.cs
- backend/Application/Api/GraphQL/Pagination/AccountTokensDescendingPagingProvider.cs
- backend/DatabaseScripts/SqlScripts/0036_AlterTable_graphql_account_tokens_add_index.sql
- backend/committed_graphql_schema.graphql
- frontend/src/components/Accounts/AccountDetailsContainer.vue
- frontend/src/components/Accounts/AccountDetailsContent.vue
- frontend/src/components/Accounts/AccountDetailsToken.vue
- frontend/src/queries/useAccountQuery.ts
- frontend/src/types/generated.ts
Adds support for tokens Pagination in Account Sidebar
Adds support for tokens Pagination in Account Sidebar
> CIS2 Tokens Pagination

- backend/Application/Api/GraphQL/EfCore/Converters/Json/TransactionResultEventConverter.cs
- backend/Application/Api/GraphQL/Import/TransactionWriter.cs
- backend/Application/Api/GraphQL/Transactions/TransactionResultEvent.cs
- backend/CHANGELOG.md
- backend/ConcordiumSdk/NodeApi/Types/JsonConverters/TransactionResultEventConverter.cs
- backend/ConcordiumSdk/NodeApi/Types/TransactionSuccessResult.cs
- backend/Tests/Api/GraphQL/Import/TransactionsWriterTest.cs
- backend/Tests/ConcordiumSdk/NodeApi/JsonConverters/TransactionResultEventConverterTest.cs
Added support for Contract Upgraded Event (Protocol 5)
Added support for Contract Upgraded Event (Protocol 5)
> Protocol 5

- backend/Application/Api/GraphQL/Import/AccountChangeCalculator.cs
- backend/Application/Api/GraphQL/Import/AccountWriter.cs
- backend/Application/Api/GraphQL/Import/BakerImportHandler.cs
- backend/Application/Api/GraphQL/Import/BakerWriter.cs
- backend/Application/Api/GraphQL/Import/IPendingBakerChangeStrategy.cs
- backend/Application/Api/GraphQL/Import/ImportWriteController.cs
- backend/Application/Api/GraphQL/Import/MetricsWriter.cs
- backend/Application/Api/GraphQL/Import/RewardsSummary.cs
- backend/CHANGELOG.md
- backend/ConcordiumSdk/NodeApi/GrpcNodeClient.cs
- backend/ConcordiumSdk/NodeApi/Types/JsonConverters/RewardStatusConverter.cs
- backend/Tests/Api/GraphQL/Import/BakerImportHandlerTests.cs
Fixes Issues https://github.com/Concordium/concordium-scan/issues/26
Moved updation of baker after baker have been added.
> Bakend : Baker update issue fix

- backend/Application/Api/GraphQL/GraphQlConfiguration.cs
- backend/Application/Api/GraphQL/Versions/Versions.cs
- backend/Application/Api/GraphQL/Versions/VersionsQuery.cs
- backend/Application/Application.csproj
- backend/CHANGELOG.md
- backend/committed_graphql_schema.graphql
- frontend/nuxt.config.ts
- frontend/src/components/PageHeader.vue
- frontend/src/components/molecules/Versions.vue
- frontend/src/queries/useVersionsQuery.ts
https://github.com/Concordium/concordium-scan/issues/38
Displaying backend and frontend versions
> Displaying backend and frontend versions

- backend/Application/Api/GraphQL/Bakers/BakerFilter.cs
- backend/Application/Api/GraphQL/Bakers/BakersQuery.cs
- backend/CHANGELOG.md
- backend/committed_graphql_schema.graphql
- frontend/src/components/Staking/BakerPools.vue
- frontend/src/pages/staking/index.vue
- frontend/src/queries/useBakerListQuery.ts
- frontend/src/types/generated.ts
Fixes https://github.com/Concordium/concordium-scan/issues/8
Updates Bakers query to include boolean filter. 
> removed bakers hidden by default

- backend/Tests/Api/GraphQL/Import/BakerImportHandlerTests.cs
- backend/Tests/Api/GraphQL/Network/ClientVersionComparerTest.cs
Minor Refactor changes for previously added test namespaces
Minor Refactor changes for previously added test namespaces
> Fixed namespace on previous tests

- backend/Application/Application.csproj
- backend/CHANGELOG.md
- backend/ConcordiumSdk/ConcordiumSdk.csproj
- backend/ConcordiumSdk/Types/Memo.cs
- backend/Tests/Api/GraphQL/Transactions/DecodedTransferMemoTests.cs
- backend/Tests/ConcordiumSdk/Transactions/AccountTransactionServiceTest.cs
- backend/Tests/ConcordiumSdk/Types/MemoTest.cs
- backend/Tests/Tests.csproj
Fixes Issue https://github.com/Concordium/concordium-scan/issues/10
Used external Library to handle CBOR decoding to string.
> Fixed CBOR decoding

- .github/workflows/ci.yml
- backend/Application/Api/GraphQL/Bakers/BakersQuery.cs
- backend/Application/Api/GraphQL/Import/BlockChangeCalculator.cs
- backend/Application/Api/GraphQL/Import/BlockWriter.cs
- backend/Tests/Api/GraphQL/Import/BlockChangeCalculatorTest.cs
- backend/Tests/Api/GraphQL/Import/EventLog/CisEventTest.cs
- backend/Tests/Api/GraphQL/Import/EventLog/EventLogWriterTest.cs
- backend/Tests/ConcordiumSdk/Types/CcdAmountTest.cs
- backend/Tests/ConcordiumSdk/Types/MemoTest.cs
- backend/committed_graphql_schema.graphql
Fixes Tests and Build
Some tests were changed and build was fixed
added CI pipeline to build on PR creation
> build fixes

- backend/Application/Api/GraphQL/Import/AccountChangeCalculator.cs
- backend/Application/Api/GraphQL/Import/AccountImportHandler.cs
- backend/Application/Api/GraphQL/Import/ImportWriteController.cs
- backend/CHANGELOG.md
- backend/Tests/Api/GraphQL/Import/AccountImportHandlerTest.cs
Fix Issue #55 
Setting account balance according to block height. 
If Block Height == 0 then actual balance is set
If Block Height > 0 then balance set is 0, Expecting the transactions to update the balance. 
> Genesis account balance bug

- backend/CHANGELOG.md
- frontend/package.json
- frontend/src/components/atoms/Amount.spec.ts
- frontend/src/components/atoms/Amount.vue
Fixes Issue #69 
Fixes Issue #69 
> 69 account statement section show wrong cost for type fee

- backend/Application/Api/Rest/BalanceStatisticsController.cs
- backend/CHANGELOG.md
Addresses Issue #75 
Addresses Issue #75 
> TotalAmountReleased endpoint

- backend/Application/Api/Rest/BalanceStatisticsController.cs
Fixes issue #66 
Fixes issue #66 
> BUG 66 : floor value when unit is CCD

- frontend/src/components/Accounts/AccountDetailsToken.vue
Addresses comment https://github.com/Concordium/concordium-scan/issues/62#issuecomment-1548390157
Addresses comment https://github.com/Concordium/concordium-scan/issues/62#issuecomment-1548390157
> aligned account sidebar tokens sections balance header to right

- backend/Application/Api/GraphQL/Import/BakerWriter.cs
A update to pool parameter has caused CCD scan to crash. This is due to a division by zero exception.
A conditional check is added which avoids division by zero when capital bopund is set to 1.
> Fix capital bound division by zero issue

- backend/Application/Api/Rest/ExportController.cs
- backend/Application/Application.csproj
- backend/CHANGELOG.md
Account balance is currently present in details view but not in exported file. This PR adds the total balance to the exported file.
* https://concordium.atlassian.net/browse/CBW-1172
Changed export statement REST API to include account statement in exported file.
> Added account balance to export

- backend/Application/Api/Rest/ExportController.cs
- backend/Application/Application.csproj
- backend/CHANGELOG.md
Added ‘Z’ to file naming such that it is clear time stamps are UTC.
From comment in 
https://concordium.atlassian.net/browse/CBW-1172
> Account balance export bug fix

- backend/Application/Aggregates/Contract/Configurations/ContractAggregateOptions.cs
- backend/Application/Aggregates/Contract/ContractAggregate.cs
- backend/Application/Aggregates/Contract/Jobs/ContractDatabaseImportJob.cs
- backend/Application/Application.csproj
- backend/Application/Program.cs
- frontend/package.json
Prepare release
- https://concordium.atlassian.net/browse/CBW-1264
- Bumped releases
- Added transient DB error handling in import job.
> Prepare release Backend 1.7.0 and Frontend 1.5.0

- frontend/package.json
- frontend/src/components/Contracts/ContractDetailsContent.vue
- frontend/src/components/DetailsCard.vue
- frontend/src/components/Drawer/DrawerContainer.vue
- frontend/src/components/Drawer/DrawerTitle.vue
- frontend/src/components/Pagination.vue
- frontend/src/queries/useModuleQuery.ts
_Describe the purpose of the pull request, link to issue describing the problem, etc.
_Describe the changes that were needed.
> UI changes

- frontend/package.json
- frontend/src/components/Contracts/ContractDetailsEvents.vue
- frontend/src/components/Tabs.vue
Fix unique id when using tabs components.
> Fix unique id

- backend/Application/Aggregates/Contract/Entities/Contract.cs
- backend/Application/Aggregates/Contract/Entities/ContractEvent.cs
- backend/Application/Aggregates/Contract/Entities/ContractRejectEvent.cs
- backend/Application/Aggregates/Contract/Entities/ModuleReferenceContractLinkEvent.cs
- backend/Application/Aggregates/Contract/Entities/ModuleReferenceEvent.cs
- backend/Application/Aggregates/Contract/Entities/ModuleReferenceRejectEvent.cs
- backend/CHANGELOG.md
Module queries were slow when it contained a lot of events. This PR refactors to using Dapper, which is same solution done for contracts.
- Change to custom sql queries instead of using Entity Framework
> Optimize module query

- frontend/src/components/Staking/BakerPools.vue
- frontend/src/pages/staking/index.vue
If you navigate to the Staking page you get a warning message in the browser console. Try on testnet
https://testnet.ccdscan.io/staking
Fix warning message by avoiding boolean to be possible undefined.
> Fix warning message on Staking page

- frontend/package.json
- frontend/src/assets/css/styles.css
- frontend/src/components/Details/Logs.vue
- frontend/src/components/Details/Message.vue
- frontend/src/components/PaginationOffset.vue
Add correct styling to messages.
Issue now seen on
https://testnet.ccdscan.io/contracts?dcount=1&dentity=contract&dcontractAddressIndex=4515&dcontractAddressSubIndex=0
> Add styling to messages

- frontend/package.json
- frontend/src/assets/css/styles.css
- frontend/src/components/Contracts/Events/ContractCall.vue
Messages and logs in hexadecimal was shown multiple times for Contract Call type.
See https://testnet.ccdscan.io/contracts?dcount=1&dentity=contract&dcontractAddressIndex=4515&dcontractAddressSubIndex=0
https://concordium.atlassian.net/browse/CBW-1256
> Fix events was shown duplicated amount of times

- backend/Application/Database/MigrationJobs/_00_UpdateValidatorCommissionRates.cs
Ensure that the job name matches the class name.
> Fix job name

- frontend/package.json
- frontend/src/components/Staking/CommissionRates.vue
Change commission rate to signal changes for new validators.
> Improve commission tooltip for new validators

- frontend/package.json
- frontend/src/components/Staking/BakerPools.vue
- frontend/src/utils/stakingAndDelegation.ts
Fix two baker mentions
https://concordium.atlassian.net/browse/CBW-1484
> Fix two baker mentions

- frontend/src/components/TransactionEventList/Events/ContractCall.vue
- frontend/src/components/TransactionEventList/Events/ContractInitialized.vue
- frontend/src/components/TransactionEventList/Events/ContractInterrupted.vue
- frontend/src/components/TransactionEventList/Events/ContractModuleDeployed.vue
- frontend/src/components/TransactionEventList/Events/ContractResumed.vue
- frontend/src/components/TransactionEventList/Events/ContractUpdated.vue
- frontend/src/components/TransactionEventList/Events/ContractUpgraded.vue
- frontend/src/components/TransactionEventList/Events/CredentialDeployed.vue
Add links to events such that one can navigate directly to entity.
> Add links to events 

- backend/Application/Application.csproj
- frontend/package.json
Bump front- and backend versions preparing for release.
> Bump front- and backend versions

- frontend/src/components/BakerDetails/BakerDetailsPoolContent.vue
- frontend/src/components/Staking/CommissionRates.vue
- frontend/src/components/Tokenomics/PaydayAccountReward.vue
- frontend/src/components/Tokenomics/PaydayFoundationReward.vue
- frontend/src/components/Tokenomics/PaydayPoolReward.vue
- frontend/src/components/TransactionEventList/Events/ChainUpdateEnqueued.vue
- frontend/src/components/molecules/ChartCards/Payday.vue
Validated Finalisation not present and changed from payday to pay day.
https://github.com/Concordium/concordium-scan/issues/2
> Fix payday to pay day

- frontend/package.json
- frontend/src/components/Navigation/Navigation.vue
- frontend/src/components/Tokens/TokenDetailsHeader.vue
- frontend/src/pages/tokens/index.vue
Change CIS2 to CIS-2 and bump frontend version
https://concordium.atlassian.net/browse/CBW-1657
> Fix CIS2 to CIS-2

- backend/Application/Application.csproj
- backend/CHANGELOG.md
> Prepare backend release 1.8.9

- backend/Application/Api/GraphQL/Search/SearchResult.cs
- backend/Application/Application.csproj
- backend/CHANGELOG.md
- frontend/package.json
Fix comment, https://github.com/Concordium/concordium-scan/pull/179#discussion_r1481130012, and bump versions.
> Fix regex comment and bump versions

- backend/Application/Application.csproj
- backend/Application/appsettings.Development.json
- backend/Application/appsettings.json
`appsettings.json` was incorrectly changed in PR https://github.com/Concordium/concordium-scan/pull/183. Changes should have been made to `appsettings.development.json`
> Fix configurations

- frontend/package.json
Bump new version with same source code to demonstrate argocd behaviour
> Bump demo version

- backend/Application/Application.csproj
- backend/CHANGELOG.md
_Describe the purpose of the pull request, link to issue describing the problem, etc.
_Describe the changes that were needed.
> Bump backend version to 1.8.13

- frontend/package.json
- frontend/src/assets/css/styles.css
- frontend/src/components/Accounts/AccountDetailsAccountStatement.vue
- frontend/yarn.lock
Fix picking month in Firefox (and safari mobile).
Use special month picker.
> Fix month picker in firefox

- backend/Application/Aggregates/Contract/Jobs/_06_AddTokenAddress.cs
- backend/Application/Application.csproj
- backend/Tests/Aggregates/Contract/Entities/TokenTestWithoutDatabase.cs
- backend/Tests/Aggregates/Contract/Jobs/_06_AddTokenAddressTest.cs
Avoid using entity framework in token address migration, since it generates timeouts.
> Improve token address migration

- frontend/package.json
> Bump frontend 1.5.39

- backend/Application/Aggregates/Contract/Jobs/ParallelBatchBlockHeightJob.cs
- backend/Application/Aggregates/Contract/Jobs/_05_CisEventReinitialization.cs
- backend/Application/Aggregates/Contract/Jobs/_06_AddTokenAddress.cs
- backend/Application/Aggregates/Contract/Jobs/_07_ContractSnapshotInitialization.cs
- backend/Application/Application.csproj
- backend/CHANGELOG.md
Some jobs throw exceptions when they were run on empty environment.
- Avoid calling functions which directly throws exceptions, if database is empty
> Fix exception from jobs on new environment

- frontend/src/components/NodeDetails/NodeDetailsContent.vue
> Fix package received

- frontend/.prettierignore
- frontend/src/assets/css/styles.css
- frontend/src/components/BakerDetails/BakerDetailsPoolAPY.vue
- frontend/src/components/Contracts/Events/contractEvents.ts
- frontend/src/components/Details/MessageHEX.vue
- frontend/src/components/Module/ModuleDetailsContainer.vue
- frontend/src/components/PassiveDelegation/PassiveDelegationContent.vue
- frontend/src/components/TransactionEventList/Events/BakerSetBakingRewardCommission.vue
- frontend/src/components/atoms/Amount.vue
- frontend/src/components/icons/ChevronDoubleLeftCustomIcon.vue
- frontend/src/components/icons/ChevronDoubleRightCustomIcon.vue
- frontend/src/components/icons/ChevronLeftCustomIcon.vue
- frontend/src/components/icons/ChevronRightCustomIcon.vue
- frontend/src/utils/infoTooltips.ts
Fix .prettierignore and run formatting
> Run frontend formatting

- .github/workflows/frontend-release.yml
Fix typo in release workflow for frontend
> Fix typo in frontend release script

- backend-rust/src/bin/ccdscan-api.rs
- backend-rust/src/bin/ccdscan-indexer.rs
https://linear.app/concordium/issue/CCD-124/allow-to-configure-connection-pool-for-api-service
Add pool params
> Pool param

- backend-rust/Cargo.lock
- backend-rust/Cargo.toml
- backend-rust/Dockerfile
Fails with ssl related error if not installed
Install openssl on the image
> Install openssl on rust image

- backend-rust/src/indexer.rs
Unblock indexer
Adding support for BakerRemoveDelegation and AccountRemoveBaker events
> Unblock Indexer

- backend-rust/src/graphql_api.rs
- backend-rust/src/graphql_api/transaction.rs
> Move Transaction and related types to separate file

- backend-rust/.sqlx/query-6e22874f1d1e7d779c1a547e91f2a2b0e7e12bc43adbe3a2cf867ee8e85c225b.json
- backend-rust/.sqlx/query-96a277e4ccd9c03a65fde62f6f11535a56aad952d45566662f8e78b43d84be34.json
- backend-rust/.sqlx/query-eeab54693b0c176aae83b9772c2809b133cf9beea62e9a45a63bc06e3a731463.json
- backend-rust/migrations/0001_initialize.up.sql
- backend-rust/src/graphql_api.rs
- backend-rust/src/graphql_api/contract.rs
- backend-rust/src/indexer.rs
Implement `Contract::contract_reject_events`
> Implement Contract::contract_reject_events

- backend-rust/src/indexer.rs
Fix build issue due to `owner` being undefined
> Fix missing 'owner' issue

- backend-rust/.sqlx/query-43d868d301d3a6e17a3877e73bacd9aa01303425c2c0c4d1ebdb11960304e821.json
- backend-rust/.sqlx/query-6d712faa16165c7ea829753d3f1562576392ff3d040250e922f1e22b89ac18b7.json
- backend-rust/.sqlx/query-6eae4a360bc13ff6f607b48dc3e241464067de0c7dd5990d46d43a737d1f5f76.json
- backend-rust/.sqlx/query-b79727933b7a9f9cbcfd69d46781fc063d1e1e80ecd9094c369c1ad15779df68.json
- backend-rust/.sqlx/query-f2c9fda1bd2ad92831aa30b765e851f2d0df12d43bc5e45d8846871d7b6595a1.json
- backend-rust/src/graphql_api.rs
- backend-rust/src/graphql_api/contract.rs
- backend-rust/src/graphql_api/token.rs
Closes https://github.com/Concordium/concordium-scan/issues/256
Add `Query::Tokens`
> Add tokens query

- backend-rust/src/address.rs
- backend-rust/src/graphql_api/contract.rs
- backend-rust/src/transaction_event/smart_contracts.rs
- backend-rust/src/transaction_event/transfers.rs
Fix minor breaking changes in the new API compared to the old, when preparing the frontend for the new backend.
> Fix minor API changes

- backend-rust/Cargo.toml
- backend-rust/src/graphql_api.rs
- backend-rust/src/graphql_api/baker.rs
- backend-rust/src/graphql_api/block.rs
- backend-rust/src/scalar_types.rs
Make `BakerId` use the `Long` scalar
> Make BakerId use the Long scalar

- backend-rust/src/graphql_api.rs
- backend-rust/src/graphql_api/baker.rs
- backend-rust/src/graphql_api/block.rs
- backend-rust/src/graphql_api/block_metrics.rs
- backend-rust/src/graphql_api/contract.rs
- backend-rust/src/graphql_api/transaction.rs
- backend-rust/src/scalar_types.rs
- backend-rust/src/transaction_event/mod.rs
- backend-rust/src/transaction_reject.rs
Expose Amount as UnsignedLong in the API of the new backend.
> Expose Amount as UnsignedLong in the API

- backend-rust/migrations/0001_initialize.up.sql
Improve processing speed for blocks with many token changes.
> Adjust index for token_index_per_contract

- backend-rust/.sqlx/query-07beeea3aaa84862e254dbb6def92838c34953e3eb4c604099f30756552f5b66.json
- backend-rust/.sqlx/query-df46fdc109db1cb09f81b2429090a1b6aa5bfc7cd37ebdd16cc0d10ee29f7000.json
- backend-rust/.sqlx/query-e841e5a107ad7eef5b804960128ae58896c87bebcabc3fba0a49648d49b38f76.json
- backend-rust/Cargo.lock
- backend-rust/Cargo.toml
- backend-rust/migrations/0001_initialize.up.sql
- backend-rust/src/address.rs
- backend-rust/src/graphql_api.rs
Implement search functions for accounts
> Account search

- backend-rust/Cargo.lock
- backend-rust/Cargo.toml
- backend-rust/src/indexer.rs
The time is still used even if multiple blocks was part of the batch.
> Fungy dashboard

- backend-rust/Cargo.lock
- backend-rust/Cargo.toml
- backend-rust/src/bin/ccdscan-indexer.rs
- backend-rust/src/indexer.rs
Default and configurable timeouts for node, logging preprocessing
> Default and configurable timeouts for node, logging preprocessing

- frontend/CHANGELOG.md
- frontend/src/queries/useChartBlockMetrics.ts
The frontend query some details in the block metrics which are never used, this PR removes those fields
> Remove unused fields in query for block metrics

- frontend/CHANGELOG.md
- frontend/src/queries/useTokenQuery.ts
Simplify query since fields are not used by the front-end.
Related to https://github.com/Concordium/concordium-scan/pull/388
> Simplify query

- backend-rust/.sqlx/query-07beeea3aaa84862e254dbb6def92838c34953e3eb4c604099f30756552f5b66.json
- backend-rust/.sqlx/query-16cf11dba48aab4e79950127b4eb20f67a32f5b8df44feb473caa2bcac46a78a.json
- backend-rust/.sqlx/query-188b2ac4ef5afdacfe2a1906c1bfa474a590ff49093401331f60b58781ccb1f0.json
- backend-rust/.sqlx/query-373de7dea3ae7994dff8fdfae038e3de77eb8ccc57c5a747ce8e7f3f585f4f50.json
- backend-rust/.sqlx/query-3c6ebfdb85f26d0ca0cf19e3e00e9e30b13e547d8c1f075c4dde7136eae72ef3.json
- backend-rust/.sqlx/query-45a77465b3e1b4895476fb81f5c29d3e36d499449e9422eb726e02a384df7d2d.json
- backend-rust/.sqlx/query-782d29aa16e457a1bdc9993e91d84927cc55e2e3bfde2be2d6aa39a5b4ff1664.json
- backend-rust/.sqlx/query-793f029fb35301b7008d0d3f7ca4467acfc69ab96a0d78ede363644d2f164a5a.json
- backend-rust/.sqlx/query-7e9e5a80542156771d0a0a017fed94b67d4a79324e63504ee7ad35222b90e789.json
- backend-rust/.sqlx/query-847daec8c3fceb973b3953d545e3854ebd057e3a6a102b568237c8133a3b59d0.json
- backend-rust/.sqlx/query-899d0b2b617a5ac3f8effc4be3295cc0eb71ccf3c6b72215eb89ee8fbd478051.json
- backend-rust/.sqlx/query-918548ae8e9e53eba8631e7d7ecc8a75bb8205eafb19d42ffba097ecd70f6d63.json
- backend-rust/.sqlx/query-93f47f7a04c67ddd9833c779cd73b662e9ef0fe2aa47787eef14924ab5bd7d65.json
- backend-rust/.sqlx/query-9d92fb18c25f73694ade310a0789709fe48098616a468bdf4b639f7b2b18aef9.json
- backend-rust/.sqlx/query-9fdd2ef5c445275b33f843e60c39f50ecad37f638509e5716e633409377b7aea.json
- backend-rust/.sqlx/query-b5a479d6a39f388d4b1c6cc868471a95f5c7cff53d6e63f0158c2337dcf3dcef.json
- backend-rust/.sqlx/query-b6e0dc87e9874d9357009d17f6475598b6f6fcb46731694e213db4bcedbdfc35.json
- backend-rust/.sqlx/query-caa2e6b17e40287c25b573b7e8be07df1f1b025848854020d8b83395a661f99b.json
- backend-rust/.sqlx/query-db4f484caba8ef401bef8838ef4dd2307f78aa97664509767d50ff6a7c3cee03.json
- backend-rust/.sqlx/query-dde8ae171c95f3839d26649e99087ea53c363f5dbfb1562e540a5be48ab38fb6.json
- backend-rust/.sqlx/query-df348e3b818510fd64f27578e842eadac44aa7c1d1908890b5ef17228eb1cfdd.json
- backend-rust/.sqlx/query-df46fdc109db1cb09f81b2429090a1b6aa5bfc7cd37ebdd16cc0d10ee29f7000.json
- backend-rust/.sqlx/query-e9fa117821f38ee7381189963a325f5dddb76455633a9778841b7f5bb2e00827.json
- backend-rust/.sqlx/query-f7dc366f7d77f81c6d1d030fc22deecf2a8aa2c1a79bbde00e721cdd12e0293a.json
- backend-rust/Cargo.lock
- backend-rust/Cargo.toml
- backend-rust/src/indexer.rs
Add remaining tracking of balances for accounts and contracts.
> Track balance updates for accounts and contracts

- .github/workflows/release-net-backend.yaml
(Hopefully) fix the release pipeline of .NET ([failing here](https://github.com/Concordium/concordium-scan/actions/runs/12864907443/job/35864357431))
> Fix release script for .NET

- backend/Application/Api/GraphQL/ChainParameters.cs
- backend/Application/Api/GraphQL/ChainParametersV3.cs
- backend/Application/Api/GraphQL/EfCore/EntityTypeConfigurations/ChainParametersConfiguration.cs
- backend/Application/Application.csproj
- backend/CHANGELOG.md
- backend/Tests/Api/GraphQL/__snapshots__/committed-schema.verified.graphql
Ensure we are compatible with new chain parameters v3
Has been tested locally against stagenet
> Chain parameters issues

- backend-rust/.sqlx/query-0a1f1c5b6d51e587b1588f03ad3fe558c34bfad5d16cdf44f20df07d1fe2ba9f.json
- backend-rust/.sqlx/query-52dace527c84c57cc61c9409795cfa5ca873fe53169af508b0a69d6d7ecea7e8.json
- backend-rust/migrations/0001_initialize.up.sql
- backend-rust/src/graphql_api.rs
- backend-rust/src/indexer.rs
> Add epoch duration query

- backend-rust/.sqlx/query-28d90f725daf9e3b8151f5c714503044fbcf80a60f4d542961e949478bbf37e2.json
- backend-rust/.sqlx/query-65bd4104ddee0fee7898948eb1716289ee1f91e0e997f9904a0da8a0fc2c0777.json
- backend-rust/.sqlx/query-70d1654528edc7b593c9b4ca7af379b4cbd670399ae7fad23e2415606f293a75.json
- backend-rust/migrations/0001_initialize.up.sql
- backend-rust/src/graphql_api.rs
- backend-rust/src/graphql_api/block.rs
- backend-rust/src/graphql_api/transaction.rs
https://linear.app/concordium/issue/CCD-81/implement-blocktransactions
> Add transactions per block query

- backend-rust/.sqlx/query-0155bbfea3d65a2b39bd5f4d3516afc4fd72e4ab84a57d775b9fabe56999a245.json
- backend-rust/.sqlx/query-0777321ac968d41e445b4bf4b536e02e01b346f3c74413fd16afb02033b485fd.json
- backend-rust/.sqlx/query-28d90f725daf9e3b8151f5c714503044fbcf80a60f4d542961e949478bbf37e2.json
- backend-rust/.sqlx/query-6d7cdf3eb927b15e8e2a21023b14f03d9a80e7f3dbe06806e8895e45fce4f6b7.json
- backend-rust/.sqlx/query-7b709bae1e9568fd76cac25703f0f0fc29ab86989796e1c8215576343de74beb.json
- backend-rust/.sqlx/query-9a6b9e071e1f6e2685f4cb1769d0f8337fee1d6d010b2cdcaa8eeab9b7546d05.json
- backend-rust/.sqlx/query-b6e0dc87e9874d9357009d17f6475598b6f6fcb46731694e213db4bcedbdfc35.json
- backend-rust/.sqlx/query-c1602c7c4f430afb0767ab9c8ff5f369e1402022a16f0c4a7d9ba197f06f0987.json
- backend-rust/migrations/0001_initialize.up.sql
- backend-rust/src/graphql_api.rs
- backend-rust/src/indexer.rs
https://linear.app/concordium/issue/CCD-72/implement-querypaydaystatus
> Add payday summary logic

- backend-rust/.sqlx/query-2af572b3665951a20d0c4ac7f1933bc014ef8e79e476921bd15622f6547e2236.json
- backend-rust/.sqlx/query-4ac2506deb151da5ab355e92728fc0d379bafa240aa6345e595fc5c32a699cd5.json
- backend-rust/.sqlx/query-56be4e24e27a63509fd07d85143368086dd706c5164e6ebbf9ba01a3aeab65b8.json
- backend-rust/.sqlx/query-c61837bbd66f728feb4c96f0582c5a6727fa1cec6604e9495423917a407b8003.json
- backend-rust/src/block_special_event.rs
- backend-rust/src/connection.rs
- backend-rust/src/graphql_api.rs
- backend-rust/src/graphql_api/block.rs
- backend-rust/src/indexer.rs
- backend-rust/src/lib.rs
- backend-rust/src/migrations/m0001-initialize.sql
- backend-rust/src/scalar_types.rs
Index block special events and implement `Block::special_events` API call
> Index and expose block special events

- backend-rust/.env.stagenet
_Describe the purpose of the pull request, link to issue describing the problem, etc.
_Describe the changes that were needed.
> Use `ccdscan_stagenet` as the default database name for stagenet env

- backend-rust/src/graphql_api/account.rs
- backend-rust/src/graphql_api/baker.rs
> Add account baker query

- backend-rust/.env.mainnet
- backend-rust/.env.stagenet
- backend-rust/.env.template
- backend-rust/.env.testnet
Add required node collector endpoints to env files.
> Add node collector envs

- backend-rust/CHANGELOG.md
- backend-rust/Cargo.lock
- backend-rust/Cargo.toml
Prepare release and introduce changelog for rust backend
> Prepare release of rust backend 0.1.19

- frontend/CHANGELOG.md
- frontend/src/components/Pagination.vue
- frontend/src/composables/usePagination.ts
Add a "Last" button for cursor pagination in the frontend.
Implemented since it is useful for testing, since it otherwise takes forever to page to old pages.
> Add last button for pagination

- backend-rust/CHANGELOG.md
- backend-rust/src/bin/ccdscan-api.rs
- backend-rust/src/graphql_api.rs
- backend-rust/src/migrations.rs
- Add `database_schema_version` and `api_supported_database_schema_version` to `versions` endpoint.
- Fix typo in `versions` endpoint.
> Improve version reporting

- backend-rust/.sqlx/query-b0028dd083e1c375585b4de47d31e41bce58086b36951adbd9cccf3210b23fb8.json
- backend-rust/CHANGELOG.md
- backend-rust/src/graphql_api/contract.rs
Invalid prev next page being returned
Change according to the rest of the queries.
> Fix prev and next page on contracts

- backend-rust/.sqlx/query-36e4dfcc33f6337ec3abbda670a4a9e07dffde8ba68145c2e519d27eadbd8b12.json
- backend-rust/.sqlx/query-3c68bcd07cc8ddee8de17f2996ece8aa625aa70aef64153347f79d84e9dd9a6b.json
- backend-rust/.sqlx/query-496b5124c54a7f21d0874859bc373fb0de9aa7dc15ae8b49bf5911be0c5f07b4.json
- backend-rust/.sqlx/query-8b160d1140d7823bcaf03711b9934621569d7e66c60aba8cb962054f82a8c2c6.json
- backend-rust/.sqlx/query-9900288397e3ef769e3e264889932596f67aa12452ce59c03a5b7960515c4036.json
- backend-rust/.sqlx/query-c07416a5848c0256f91d348fa9e6ecd57314b324797202fd0f34dc62f5a6561d.json
- backend-rust/.sqlx/query-c70916cfc9c9c93317085de3593fcf3489e5e03b16eeeef204d4886a30471cce.json
- backend-rust/.sqlx/query-d2b1b263ea1e5f7137508c5ef4c9e6ad100dfb110542456c98575729594ca57a.json
- backend-rust/CHANGELOG.md
- backend-rust/src/graphql_api/contract.rs
Task: https://linear.app/concordium/issue/CCD-169/contract-rejected-event-size
> Contract rejected event

- backend-rust/CHANGELOG.md
- backend-rust/src/transaction_event/smart_contracts.rs
> Return null for contract update message when parameter is empty

- backend-rust/.sqlx/query-f7cea6fd106fa6d9b6ce998e7db732015fb7fe7df866989bda653fb3f169c60a.json
- backend-rust/CHANGELOG.md
- backend-rust/src/graphql_api/token.rs
> Reverse item ordering for Token::token_events.

- backend-rust/CHANGELOG.md
- backend-rust/src/migrations/m0002-block-cumulative-fin-time-index.sql
> Fix date_bin_series to not include bucket in future

- backend-rust/CHANGELOG.md
- backend-rust/Cargo.lock
- backend-rust/Cargo.toml
Prepare release of rust backend 0.1.21
> Prepare release rust backend 0.1.21

- frontend/CHANGELOG.md
- frontend/package.json
Prepare front-end release 1.7.1
> Prepare front-end release

- backend-rust/CHANGELOG.md
- backend-rust/src/indexer.rs
Add option to limit the requests for the node
> Add options to limit the requests for the node

- backend-rust/CHANGELOG.md
- backend-rust/src/graphql_api/token.rs
> Fix Query::tokens page info

- backend-rust/CHANGELOG.md
- backend-rust/Cargo.lock
- backend-rust/Cargo.toml
Release 0.1.22 of the rust backend
> Prepare release of rust backend 0.1.22

- backend-rust/CHANGELOG.md
- backend-rust/Cargo.lock
- backend-rust/Cargo.toml
I need the metrics to be included
> Bump version

- backend-rust/CHANGELOG.md
- backend-rust/src/indexer.rs
> Improve performance get source module

- backend-rust/CHANGELOG.md
- backend-rust/Cargo.lock
- backend-rust/Cargo.toml
> Rust backend 0.1.25 release

- backend-rust/CHANGELOG.md
- backend-rust/Cargo.lock
- backend-rust/Cargo.toml
- backend-rust/src/indexer.rs
- backend-rust/src/migrations.rs
- backend-rust/src/migrations/m0009_pool_info_constraint.sql
Fix constraint on poolsize and removal of duplication on affected accounts
> Fix constraint on poolsize and removal of duplication on affected accounts

- backend-rust/CHANGELOG.md
- backend-rust/Cargo.lock
- backend-rust/Cargo.toml
- backend-rust/src/indexer.rs
Same as https://github.com/Concordium/concordium-scan/pull/553 but for additional queries.
> Baker validation

- backend-rust/CHANGELOG.md
- backend-rust/src/graphql_api/baker.rs
Closes https://github.com/Concordium/concordium-scan/issues/558
> Read node status when querying a baker

- backend-rust/CHANGELOG.md
- backend-rust/src/graphql_api/baker.rs
- backend-rust/src/indexer.rs
> Fix ranking of bakers

- backend-rust/CHANGELOG.md
- backend-rust/src/graphql_api/baker.rs
- backend-rust/src/graphql_api/node_status.rs
Attach additional fields required as part of NodeStatus
Add node_status endpoint
No corresponding issue has been created.
I altered the recurring node_status field, to instead only contain the data required.
There is an issue when a node is click which is no longer present (Should also be an issue on the existing UI). A task has been created: https://linear.app/concordium/issue/CCD-203/node-collector-changes
> Node status

- backend-rust/CHANGELOG.md
- backend-rust/Cargo.lock
- backend-rust/Cargo.toml
- frontend/CHANGELOG.md
- frontend/package.json
- frontend/src/queries/useBakerMetricsQuery.ts
Use new frontend on baker metrics query
> Bump CCDScan versions

- backend-rust/src/graphql_api/transaction.rs
Change total count to be the total length of the underlying dataset
**Note** changelog was updated in another PR, and no release has been made since
> Fix total count

- backend-rust/CHANGELOG.md
- backend-rust/Cargo.lock
- backend-rust/Cargo.toml
- frontend/CHANGELOG.md
- frontend/package.json
> Bump versions

- backend-rust/CHANGELOG.md
- backend-rust/Cargo.lock
- backend-rust/Cargo.toml
- frontend/CHANGELOG.md
- Back-end and Front-end releases.
> Back-end and Front-end releases

- backend-rust/CHANGELOG.md
- backend-rust/src/migrations.rs
- backend-rust/src/migrations/m0020_amounts_schedule.rs
- backend-rust/src/transaction_event/mod.rs
- backend-rust/src/transaction_event/transfers.rs
Closes https://github.com/Concordium/concordium-scan/issues/599
and finishes [CCD-201/frontend-transaction-details](https://github.com/Concordium/concordium-scan/issues/560)
Finish up amount schedule
> Amount schedule

- backend-rust/CHANGELOG.md
- backend-rust/src/graphql_api/account.rs
- backend-rust/src/migrations.rs
> Fix transaction count value

- backend-rust/CHANGELOG.md
- backend-rust/Cargo.lock
- backend-rust/Cargo.toml
- backend-rust/src/transaction_event/chain_update.rs
Validator param is not compatible with dotnet
> Fix validator param name

- backend-rust/CHANGELOG.md
- backend-rust/src/bin/ccdscan-api.rs
- backend-rust/src/bin/ccdscan-indexer.rs
> Adjust default log filter when using --log-level

- frontend/CHANGELOG.md
- frontend/src/queries/usePassiveDelegationQuery.ts
> Migrate passive delegation

- backend-rust/.sqlx/query-9124dfc5c7e260e515cebc2810a1b82c14e30e9082e48e2af253a8949a0b2453.json
- backend-rust/CHANGELOG.md
- backend-rust/src/transaction_event/baker.rs
- backend-rust/src/transaction_event/chain_update.rs
- frontend/src/queries/useTransactionQuery.ts
Closes https://github.com/Concordium/concordium-scan/issues/597
> Remove todo apis on transaction event baker

- backend-rust/CHANGELOG.md
- backend-rust/src/graphql_api/contract.rs
- backend-rust/src/migrations.rs
- backend-rust/src/migrations/m0023_add_init_parameter.rs
- backend-rust/src/transaction_event/mod.rs
- backend-rust/src/transaction_event/smart_contracts.rs
Closes https://github.com/Concordium/concordium-scan/issues/303
_Describe the changes that were needed.
> Add input parameter decoding for init functions

- backend-rust/README.md
- backend-rust/src/migrations.rs
Improve documentation regarding database migration in READ.me
> Improve readme regarding database migration

- backend-rust/CHANGELOG.md
- backend-rust/src/graphql_api/baker.rs
> Fix accidental breaking change for BakerSort apy variants

- frontend/CHANGELOG.md
- frontend/src/components/SuspendedValidators/PrimedForSuspensionValidators.vue
- frontend/src/components/SuspendedValidators/SuspendedValidators.vue
- frontend/src/components/SuspendedValidators/SuspendedValidatorsContainer.vue
- frontend/src/components/SuspendedValidators/SuspendedValidatorsContent.vue
- frontend/src/composables/usePagination.ts
> Add pagination for suspended validators and primed for suspension lists

- frontend/.husky/pre-commit
- frontend/README.md
- frontend/package.json
> Remove husky pre commit hook

- backend-rust/.sqlx/query-d32b36ee99c60d4e79bac1ff9419cdfc10c60cc29254401478cb0969c3578b87.json
- backend-rust/CHANGELOG.md
- backend-rust/src/indexer.rs
- backend-rust/src/migrations.rs
- backend-rust/src/migrations/m0026_update_genesis_validator_info.rs
> Fix missing information for pools existing prior to P4

- backend-rust/CHANGELOG.md
- backend-rust/src/indexer.rs
- backend-rust/src/migrations.rs
- backend-rust/src/migrations/m0027_reindex_credential_deployments.rs
- backend-rust/src/transaction_event/mod.rs
> Reindex credential deployments

- backend-rust/CHANGELOG.md
- backend-rust/Cargo.lock
- backend-rust/Cargo.toml
- frontend/CHANGELOG.md
- frontend/package.json
Prepare release of rust backend and frontend
> Prepare release

- backend-rust/CHANGELOG.md
- backend-rust/Cargo.lock
- backend-rust/Cargo.toml
> Prepare rust backend release 0.1.45

- backend-rust/.sqlx/query-331df74ca362cfd09ac8e2554f1e05fb697b670d2894e6fce5c4ec05e5d8a0cb.json
- backend-rust/.sqlx/query-cb72a248d20ae67bc02edfc2f744b6f5147740e38557c84dba81c189ceb4c100.json
- backend-rust/CHANGELOG.md
- backend-rust/src/bin/ccdscan-api.rs
- backend-rust/src/graphql_api.rs
- backend-rust/src/lib.rs
- backend-rust/src/rest_api.rs
> Support exporting accounts statements from rust backend

- backend-rust/.sqlx/query-0aa428c07aee238cc8590dfbc32055895c96e26696217b214da814c108919e7d.json
- backend-rust/.sqlx/query-2cb24f8f1826a4dee5b652fb0c20bbdd90f686d6504034e81875bdc4b33f12a2.json
- backend-rust/.sqlx/query-303f0cab34eb3df8a25d0499a51435db928f3a128c12e5f67a34a68e63a56048.json
- backend-rust/.sqlx/query-496b5124c54a7f21d0874859bc373fb0de9aa7dc15ae8b49bf5911be0c5f07b4.json
- backend-rust/.sqlx/query-70d6ffee6279732a9c95e3eb5fe7ad7f832be1fcc8a91d8fdc0d0717f65523b0.json
- backend-rust/.sqlx/query-79524f9943d92565a99d0dedfa766f55e28d2153a23dc9b3a099b4e1905fa411.json
- backend-rust/.sqlx/query-7ac492429c68166d50d91fb43215af30471506920ac7274d7aa0ff733cf94357.json
- backend-rust/.sqlx/query-8b160d1140d7823bcaf03711b9934621569d7e66c60aba8cb962054f82a8c2c6.json
- backend-rust/.sqlx/query-90eb6256da2b7725f64955ba77448390047c2f65468ec6a5dad561fb8dc66d65.json
- backend-rust/.sqlx/query-9900288397e3ef769e3e264889932596f67aa12452ce59c03a5b7960515c4036.json
- backend-rust/.sqlx/query-d2b1b263ea1e5f7137508c5ef4c9e6ad100dfb110542456c98575729594ca57a.json
- backend-rust/.sqlx/query-fe76c42d2d3cadaa2625ab7605ac8f4b00845f7f4660c77d6e16a089d16fd571.json
- backend-rust/CHANGELOG.md
- backend-rust/src/graphql_api/baker.rs
- backend-rust/src/graphql_api/contract.rs
- backend-rust/src/graphql_api/search_result.rs
Closes https://github.com/Concordium/concordium-scan/issues/454
- Add `SearchResult::bakers` 
- Add `SearchResult::contracts`
> Add search queries

- backend-rust/.sqlx/query-88fdad9296550f37676177d2c1b101e8fb9eaf397bc6710aac04cfe79447b0c0.json
- backend-rust/.sqlx/query-eaeae676550301d2d3b2f14dc200ef41a182b23bbe948bde835114f5d247bcc3.json
- backend-rust/CHANGELOG.md
- backend-rust/src/bin/ccdscan-api.rs
- backend-rust/src/graphql_api.rs
- backend-rust/src/rest_api.rs
> Add balance statistics to REST API

- frontend/CHANGELOG.md
- frontend/package.json
Add a new environment configuration enablePltFeatures to control the display of the stable coin menu.
This feature flag will allow enabling or disabling PLT-related features based on environment variables.
- Added enablePltFeatures config in frontend/nuxt.config.ts.
- Defaulted the feature flag to false.
- Bumped project version from 1.7.12 to  1.7.13.
- Updated CHANGELOG.md to include the new configuration addition.
> chore(changelog): resolve conflicts

- backend-rust/Cargo.lock
Use the main branch of the rust sdk submodule
> Update rust sdk submodule to use the main branch

- backend-rust/.sqlx/query-9f91c92d6ee70c7e4b8abe7f7f2653b5479b6b1ca739ea0f815b6d4d2118f658.json
- backend-rust/CHANGELOG.md
- backend-rust/src/graphql_api/baker.rs
Pagination is not working properly for baker transactions
Linear task:
https://linear.app/concordium/issue/SRE-1153/incorrect-page-info-for-baker-transactions
> Baker transaction pagination

- README.md
- backend-rust/CHANGELOG.md
- backend-rust/schema.graphql
- frontend/CHANGELOG.md
- frontend/README.md
- frontend/graphql-codegen.yml
- frontend/src/components/StableCoin/Holders.vue
- frontend/src/components/Tokens/Events/CisBurnEventDetails.vue
- frontend/src/components/Tokens/Events/CisMintEventDetails.vue
- frontend/src/components/Tokens/Events/CisTransferEventDetails.vue
- frontend/src/components/molecules/ChartCards/CumulativeAccountsCreatedChart.vue
- frontend/src/components/molecules/ChartCards/CumulativeTransactionsChart.vue
- frontend/src/components/molecules/ChartCards/RewardMetricsForAccountChart.vue
- frontend/src/components/molecules/ChartCards/StableCoinTokenDistributionByHolder.vue
- frontend/src/components/molecules/ChartCards/TotalRewardsChart.vue
- frontend/src/queries/useStableCoinDashboardList.ts
- frontend/src/queries/useStableCoinLatestTransactionsQuery.ts
- frontend/src/queries/useStableCoinTokenTransferQuery.ts
- frontend/src/types/generated.ts
Generated types by the graphQL schema and imported in vue files
- Generated types by the graphQL schema 
- Imported types from generated file and mapped them where it needed to be 
- Ensure no type check issues 
> Generated types by the graphQL schema and imported in vue files

- backend-rust/CHANGELOG.md
- backend-rust/src/graphql_api.rs
Adding playground to the API, since graphiQL is down at the moment.
> Add playground to the API

- backend-rust/CHANGELOG.md
- backend-rust/src/graphql_api/node_status.rs
- Fix missing `ema` and `emsd` values.
> Fix missing ema and emsd values (COR-1380)

- backend-rust/CHANGELOG.md
- backend-rust/README.md
- backend-rust/src/bin/ccdscan-indexer.rs
- backend-rust/src/indexer.rs
- backend-rust/src/migrations.rs
> Add indexer lock preventing multiple indexers running

- backend-rust/CHANGELOG.md
- backend-rust/src/graphql_api.rs
- backend-rust/src/graphql_api/account.rs
- backend-rust/src/graphql_api/baker.rs
- backend-rust/src/graphql_api/baker_and_delegator_types.rs
- backend-rust/src/graphql_api/baker_metrics.rs
- backend-rust/src/graphql_api/block_metrics.rs
- backend-rust/src/graphql_api/contract.rs
- backend-rust/src/graphql_api/module_reference_event.rs
- backend-rust/src/graphql_api/node_status.rs
- backend-rust/src/graphql_api/passive_delegation.rs
- backend-rust/src/graphql_api/search_result.rs
- backend-rust/src/graphql_api/token.rs
- backend-rust/src/graphql_api/transaction.rs
- backend-rust/src/transaction_event/baker.rs
- backend-rust/src/transaction_event/mod.rs
- backend-rust/src/transaction_event/smart_contracts.rs
- backend-rust/src/transaction_event/transfers.rs
> Hide internal errors in API and log these instead

- backend-rust/CHANGELOG.md
- backend-rust/Cargo.lock
- backend-rust/Cargo.toml
Bump backend-rust version
Updated changelog and cargo.toml
> chore: bump version to 2.0.4

- backend-rust/Dockerfile
Fix docker file to consider the mock data flies
Dockerfile changed
> fix: dockerfile for mock data

- backend-rust/CHANGELOG.md
- backend-rust/Cargo.lock
- backend-rust/Cargo.toml
> update:bump version 2.0.5

- backend/CHANGELOG.md
- backend/src/migrations/m0024-baker-apy-materialized-view.sql
Migration 24 failed when running against PostgreSQL 17.5, this PR adds fixes for the errors.
> Fix migration 24 which fails when running PostgreSQL 17.5

- backend/CHANGELOG.md
- backend/Cargo.lock
- backend/Cargo.toml
Changelog updated for the next release to be tagged today
Updating changelog moving fixes to 2.0.8 release
> fix: updated changelog for 2.0.8 release

- backend/Cargo.lock
- backend/Cargo.toml
Bump cargo toml version for release
update cargo toml to 2.0.9
> fix: bumping cargo toml version

- frontend/CHANGELOG.md
- frontend/package.json
Bump version
Updated changelog and packge.json
> bump-version: frontend

- frontend/CHANGELOG.md
- frontend/package.json
Bump frontend version
Changelog and package.json are updated.
> chore: update changelog and package.json

- backend/CHANGELOG.md
- backend/Cargo.lock
- backend/Cargo.toml
Bump version 2.0.15
Cargo.toml and CHANGELOG.md is Updated
> chore: bump backend 2.0.15

- frontend/CHANGELOG.md
- frontend/src/components/RejectionReason/Reasons/TokenModuleReject.vue
- frontend/src/components/molecules/ChartCards/StableCoinDistributionChart.vue
- frontend/src/composables/usePagedData.ts
- frontend/src/pages/protocol-token/index.vue
- frontend/src/queries/usePltEventsQuery.ts
Bug fix  
1. https://linear.app/concordium/issue/CRE-425/bug-available-balance-and-required-balance-are-blank
2. https://linear.app/concordium/issue/CRE-426/bug-supply-pie-chat-is-showing-wrong-data
Above mentioned bugs are fixed .
`usePagedData` composable now accepts optional parameter pageSize and pageMaxSize 
> fix: bug Related to CRE-425 and CRE-426

- frontend/CHANGELOG.md
- frontend/package.json
Frontend bump version 1.7.21
package.json and changelog updated
> chore: frontend bump version 1.7.21 Part of CRE-425, CRE-426

- backend/CHANGELOG.md
- backend/src/migrations/m0037_update_transaction_type_add_tokenupdate.rs
Introducing batches to the script and adding more logging to show the progress.
The overall running of this particular script would still be quite a while, expect possibly a few days due to the large tables involved. The log should print how many rows are processed at the time of running, indicating the process is still running
and how far it has gone through.
Added batching to the update statements, with size of 10k records. 
Added logging to show progress of the batches.
> Introduced batches to file m0037

- frontend/CHANGELOG.md
- frontend/package.json
Bump frontend 1.7.22
Package.json and Changelog updated
> bump-version: frontend/1.7.22

- frontend/CHANGELOG.md
- frontend/package.json
Bump version 1.7.23 
package.json and changelog updated
> bump version: frontend

- frontend/src/components/atoms/PltAmount.vue
UI Changes requested by the Team
> fix CRE-556

- backend/CHANGELOG.md
- backend/Cargo.lock
- backend/Cargo.toml
Bump version to 2.0.21
cargo.toml and Changelog are updated
> Bump version backend 2.0.21

- frontend/CHANGELOG.md
- frontend/package.json
Bump frontend 1.7.26
Changelog and package.json are updated
> bump frontend

- backend/Dockerfile
Fix dockerfile 
Remove mockfiles copy from dockerfile
> fix dockerfile
